export const UPDATE_SEARCH_QUERY = "UPDATE_SEARCH_QUERY";
export const ADD_STATE = "ADD_STATE";
export const REMOVE_STATE = "REMOVE_STATE";
export const UPDATE_FILTER_STATE = "UPDATE_FILTER_STATE";
export const RESET_FILTER_STATE = "RESET_FILTER_STATE";
export const RESET_QUERY_STATE = "RESET_QUERY_STATE";
export const RESET_ALL_FILTER_STATES = "RESET_ALL_FILTER_STATES";
